version: '3.7'
services:
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - .:/var/www/html
        tty: true
        stdin_open: true

    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 80:80
        links:
            - php
            - mysql
            - redis
            - node
        volumes:
            - .:/var/www/html

    mysql:
        build: ./docker/mysql
        command: --default-authentication-plugin=mysql_native_password
        # restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: localhost
            MYSQL_DATABASE: localhost
            MYSQL_USER: localhost
            MYSQL_PASSWORD: localhost
        volumes:
            - mysql-data:/var/lib/mysql
            - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    redis:
        build: ./docker/redis
        ports:
            - 6379:6379
        volumes:
            - redis-data:/var/lib/redis/

    mailhog:
        image: mailhog/mailhog
        ports:
            # 8025 -> ブラウザ参照画面
            # 1025 -> smtp port
            - 8025:8025
volumes:
    mysql-data:
        driver: local
    redis-data:
        driver: local
